### ISSUE TITLE
Add support for removing detach particles

### ISSUE THREAD

**Issue by danikov** [Synthlight/Hardspace-Shipbreaker-Furnace-Performance-Improvement-Mod#1]
Same kind of slowdown seems to occur when detaching an object at close range, would it be possible to disable those particles as well?

**Comment by Synthlight** [comment]
Possible? Yes. It doesn't fall in the scope of this mod though. (_If_ I were to do it, it would be a different mod/repo.)
As of right now though, this is minor enough for me that I have no motivation to do it. If you know which class/methods cause this I can probably whip up something relatively quickly, but finding that spot can be tricky.
